[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.backends.legacy:build"

[project]
name = "nut2mqtt"
version = "1.4.0"
description = "A NUT to MQTT bridge for Home Assistant"
requires-python = ">=3.10"
dependencies = [
    "paho-mqtt",
    "pyyaml",
]

[tool.bumpversion]
current_version = "1.4.0"
commit = true
tag = true
tag_name = "v{new_version}"
message = "Release {new_version}"

[[tool.bumpversion.files]]
filename = "nut2mqtt.py"
search = '__version__ = "{current_version}"'
replace = '__version__ = "{new_version}"'

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'
